### ISSUE TITLE
Support MySQL 5.5

### ISSUE THREAD

**Issue by ghazel** [kjellm/munin-mysql#34]
Use of uninitialized value in printf at /etc/munin/plugins/mysql_innodb_insert_buf line 1099.

Happens with mysql_innodb_insert_buf, mysql_innodb_insert_buf_size and mysql_innodb_io_pend using MySQL 5.5.8.

Here are the relevant sections of the `SHOW ENGINE INNODB STATUS\G` output

```
--------
FILE I/O
--------
I/O thread 0 state: waiting for completed aio requests (insert buffer thread)
I/O thread 1 state: waiting for completed aio requests (log thread)
I/O thread 2 state: waiting for completed aio requests (read thread)
I/O thread 3 state: waiting for completed aio requests (read thread)
I/O thread 4 state: waiting for completed aio requests (read thread)
I/O thread 5 state: waiting for completed aio requests (read thread)
I/O thread 6 state: waiting for completed aio requests (write thread)
I/O thread 7 state: waiting for completed aio requests (write thread)
I/O thread 8 state: waiting for completed aio requests (write thread)
I/O thread 9 state: waiting for completed aio requests (write thread)
Pending normal aio reads: 1 [0, 1, 0, 0] , aio writes: 0 [0, 0, 0, 0] ,
 ibuf aio reads: 0, log i/o's: 0, sync i/o's: 0
Pending flushes (fsync) log: 0; buffer pool: 0
5528380 OS file reads, 19874402 OS file writes, 615327 OS fsyncs
19.95 reads/s, 16384 avg bytes/read, 30.74 writes/s, 3.22 fsyncs/s


-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 206, free list len 23078, seg size 23285, 202193 merges
merged operations:
 insert 496342, delete mark 22556, delete 3840
discarded operations:
 insert 1686, delete mark 2, delete 0
Hash table size 57374437, node heap has 54332 buffer(s)
87022.67 hash searches/s, 7098.93 non-hash searches/s
```

**Comment by danvaida** [comment]
sorry for posting in a closed issue: @ovizii have you managed to get this sorted? thanks.

**Comment by ovizii** [comment]
@danvaida - no I didn't, simply gave up. Couldn't figure it out on my own, no hints as to what is wrong, just stopped working. I guess I'll have to live with this until maybe a future version sorts this out again.

**Comment by danvaida** [comment]
did you see this https://github.com/munin-monitoring/munin/pull/109/ ?

**Comment by ovizii** [comment]
Ah, my mistake, I thought I had the munin version that includes that fix already (apparently it should be included in: 2.1.3.) and only now when you asked I realized I am running munin: 2.0.25-1~bpo70+1 

Let me check if I can upgrade my munin or apply those patched manually.

The only thing I am wondering about is why it was working before???

**Comment by ovizii** [comment]
I'm now running: This page was generated by Munin version 2.1.9-1 from the experimental Debian branch and its seems I still have the exact same problem: 

2015/01/05-19:30:15 [824524]    Unknown section: INDIVIDUAL BUFFER POOL INFO at /etc/munin/plugins/mysql_slow line 1099.
2015/01/05-19:30:15 [824524] Service 'mysql_slow' exited with status 255/0.
2015/01/05-19:30:15 [824524] Error output from mysql_tmp_tables:
2015/01/05-19:30:15 [824524]    Unknown section: INDIVIDUAL BUFFER POOL INFO at /etc/munin/plugins/mysql_tmp_tables line 1099.
2015/01/05-19:30:15 [824524] Service 'mysql_tmp_tables' exited with status 255/0.
2015/01/05-19:30:17 [824524] Error output from mysql_innodb_bpool:
2015/01/05-19:30:17 [824524]    Unknown section: INDIVIDUAL BUFFER POOL INFO at /etc/munin/plugins/mysql_innodb_bpool line 1099.
2015/01/05-19:30:17 [824524] Service 'mysql_innodb_bpool' exited with status 255/0.
2015/01/05-19:32:11 Server closing!

Will probably revert back to the stable munin version asap :-(

**Comment by danvaida** [comment]
do you have line "'INDIVIDUAL BUFFER POOL INFO' => \&skip," ? it's on line 1075 in commit https://github.com/y-ken/munin/commit/9f53020cc7aa5338b9983cab3c1f233ffd349576

**Comment by ovizii** [comment]
No I don't :-( check here: http://screencast.com/t/Ou4e6Aijl

So what I did was this: 
'apt-get install -t experimental munin munin-common munin-doc munin-node munin-plugins-core munin-plugins-extra -u'

which installed Munin version 2.1.9-1

**Comment by ovizii** [comment]
and btw. my munin install is now completely dead with version 2.1.9-1 :-/ 
the only thing I can find in the lgos that looks suspicious is: 
The following errors were reported by munin-node-configure --shell --newer 2.0.6
# FATAL: version '2.0.6' was not found in the plugin history file
Jan 06 20:50:35 - Starting munin-node-configure --shell --newer 2.0.6

Any ideas which logs to check and how to debug? 
It just stopped working => https://foo.dj/munin/stratoserver.net/h2118175.stratoserver.net/index.html

Next I started playing around with: munin-node-configure --suggest 
and found a few unused plugins that were giving errors so I deleted them in the hopes of fixing this problem. And indeed it started working again but a few other modules now stopped. *sigh* gotta go fix those now, check the link above.

P.S. MYSQL now seems to be working too.
