### ISSUE TITLE
trying to get multi-instance working

### ISSUE THREAD

**Issue by ghost** [kjellm/munin-mysql#48]
referencing this - https://github.com/kjellm/munin-mysql/issues/22

I am trying to get multi-instances working with the mysql munin plugin.

Setup as follows (password removed)

[mysql_4407_*]
env.mysqlconnection DBI:mysql:mysql;host=localhost;port=4407;mysql_socket=/var/lib/mysql-4407/mysql.sock
env.mysqluser root

[mysql_5507_*]
env.mysqlconnection DBI:mysql:mysql;host=localhost;port=5507;mysql_socket=/var/lib/mysql-5507/mysql.sock
env.mysqluser root

[mysql_6607_*]
env.mysqlconnection DBI:mysql:mysql;host=localhost;port=6607;mysql_socket=/var/lib/mysql-6607/mysql.sock
env.mysqluser root

I then added symlinks in the plugins dir.

lrwxrwxrwx. 1 root root 30 May  1 16:58 /etc/munin/plugins/mysql -> /usr/share/munin/plugins/mysql
lrwxrwxrwx. 1 root root 30 May  2 13:03 /etc/munin/plugins/mysql_4407 -> /usr/share/munin/plugins/mysql
lrwxrwxrwx. 1 root root 30 May  2 13:03 /etc/munin/plugins/mysql_5507 -> /usr/share/munin/plugins/mysql
lrwxrwxrwx. 1 root root 30 May  2 13:03 /etc/munin/plugins/mysql_6607 -> /usr/share/munin/plugins/mysql

my munin-server sees all the instances... and creates "space" for them all but after 24 hours no graphs are being rendered.  I have all the headers and boxes with question marks.  

I can query from telnet from my server;
# munin node at replicant1.tor.fmpub.net

fetch mysql_4407
multigraph bin_relay_log-4407
Binlog_cache_disk_use.value 0
Binlog_cache_use.value 0
ma_binlog_size.value 0
relay_log_space.value 305286517
multigraph commands-4407
Com_replace_select.value 0
Com_update_multi.value 0
Com_insert_select.value 114
Com_delete_multi.value 0
Com_load.value 0
Com_delete.value 141103
Com_replace.value 0
Com_update.value 6579

Could you verify that I have things setup properly and perhaps give me some advice on how to fix the graphing?

**Comment by mozzee** [comment]
same here, I tried to configure two mysql instance but it only update the graph of first instance. While for the other it gives warning messages like 

2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_myisam_key_cache which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_tmp_tables which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_innodb_rows which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_qcache which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_innodb_read_views which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_innodb_io which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_innodb_tnx which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_innodb_semaphores which already exists on that host.  Deleting new data.
2017/06/04 08:40:04 [WARNING] Service collision: plugin mysql_localhost on localhost/127.0.0.1:4949 reports mysql_qcache_mem which already exists on that host.  Deleting new data.

**Comment by Offerkohen** [comment]
hello, any update on this please.

**Comment by niclan** [comment]
The log shows something I should have understood earlier: Since this is a multigraph plugin it itself says what part of the namespace it inhabits. Even if we change names of the plugin in configuration what the plugin says takes priority.  The only way to solve this is to make use of this patch: https://github.com/kjellm/munin-mysql/commit/9b4d859d06f1f7597006cef6408ef9935aa20d0e which is in master. Each instance of the plugin has to be associated with a different hostname.  And then you need to configure your munin master to retrieve information on the "different hostname" from the node where it is configured.
