### ISSUE TITLE
Mentioned Debian packaging meta

### ISSUE THREAD

**Issue by szepeviktor** [kjellm/munin-mysql#82]
> yyuu provides a fork containing the packaging meta files for Debian/Ubuntu systems. You can use these to build a Debian package. The fork can be found at https://github.com/yyuu/munin-mysql/

Could it be that actually there are no Debian files in @yyuu 's fork?

**Comment by kjellm** [comment]
Not sure what has happened here. I'll remove this part from the README

**Comment by yyuu** [comment]
I'm not sure what as hppened. Anyway I'm not using munin anymore and it'd be better to remove it from README.
