### ISSUE TITLE
munin mysql plugin errors

### ISSUE THREAD

**Issue by Blisk** [kjellm/munin-mysql#90]
Just setup munin on centos 7.2 and geting alot of errors in log.
Any idea what can be wrong??
2016/10/07-15:10:13 [27762]     Use of uninitialized value in printf at /etc/munin/plugins/mysql_innodb_tnx line 886.
2016/10/07-15:10:13 [27762] Error output from mysql_innodb_semaphores:
2016/10/07-15:10:13 [27762]     Use of uninitialized value in printf at /etc/munin/plugins/mysql_innodb_semaphores line 886.
2016/10/07-15:10:13 [27762] Error output from mysql_forum:
2016/10/07-15:10:13 [27762]     Unknown graph forum at /etc/munin/plugins/mysql_forum line 832.
2016/10/07-15:10:13 [27762] Service 'mysql_forum' exited with status 255/0.
2016/10/07-15:10:13 [27762] Error output from mysql_forum:
2016/10/07-15:10:13 [27762]     Unknown graph forum at /etc/munin/plugins/mysql_forum line 875.
2016/10/07-15:10:13 [27762] Service 'mysql_forum' exited with status 255/0.
2016/10/07-15:10:13 [27762] Error output from mysql_innodb_bpool:
2016/10/07-15:10:13 [27762]     Use of uninitialized value in printf at /etc/munin/plugins/mysql_innodb_bpool line 886.
2016/10/07-15:10:16 [27762] Error output from mysql_innodb_insert_buf:
2016/10/07-15:10:16 [27762]     Use of uninitialized value in printf at /etc/munin/plugins/mysql_innodb_insert_buf line 886.
2016/10/07-15:10:04 [27762] Error output from mysql_replication:
2016/10/07-15:10:04 [27762]     Use of uninitialized value in printf at /etc/munin/plugins/mysql_replication line 886.
2016/10/07-15:10:04 [27762]     Use of uninitialized value in printf at /etc/munin/plugins/mysql_replication line 886.
2016/10/07-15:10:07 [27762]     Use of uninitialized value in printf at /etc/munin/plugins/mysql_innodb_io_pend line 886.

**Comment by roidelapluie** [comment]
Those files do not come from this project..
